### ISSUE TITLE
[Bug Report] Crash on world load when Terralith is installed

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Hennamann/Fog-Tweaker#12]
Minecraft version: 1.18.1
Fogtweaker: 1.4.0
Forge version: 39.0.79

Crash report: https://gist.github.com/TheDeviantCrafter/85ce008df3620de779ca9aaa1ac3287e

The issue happens as soon as I open a singleplayer world. New and old worlds are both affected.

**Comment by TheDeviantCrafter** [comment]
The configs appear to generate correctly.

My pack has Teralith 2.0 which adds new biomes. These don't appear in the `config/fogtweaker/biomes` folder. That mod is designed to work when entirely server-side, so it might be doing something funky with the biome registry.

**Comment by TheDeviantCrafter** [comment]
I replicated the crash with just Terralith and Fog Tweaker. Disabling Terralith fixed the crash.

Crash report: https://gist.github.com/TheDeviantCrafter/e3ff91cd7b6f167038e8d2f3eb2fdef9

**Comment by TheDeviantCrafter** [comment]
One of the devs in the Stardust Labs Discord chimed in:

glanced glanced at the log - pretty sure Terralith would not have anything to do with it (directly). like you said, its probably some weird conflict, but it would have to be fixed on Fog Tweaker's end, not Terraliths' (since there isnt anything Terralith can do about it)
although it seems like, a very odd conflict
because Terralith wouldnt affect the poison event handler

**Comment by Hennamann** [comment]
Thanks for narrowing it down to being related to Terralith, i'll have to do some testing. Seeing as it's only happening with the poison event handler it might be a (simple) server vs client issue…

**Comment by Hennamann** [comment]
So the issue seems to arise from datapack biomes not being available in the Forge/Vanilla registry like modded biomes are. 

I'll need to look into ways of potentially fixing this, but until then i have created an experimental version that disables config loading for biomes from terralith, you can download it from the maven here: https://maven.henrikstabell.com/mods/com/henrikstabell/fogtweaker/FogTweaker-1.18.1/1.4.1/FogTweaker-1.18.1-1.4.1.jar This of course also means that Fog Tweaker cannot be used to customize fog in Terralith biomes (or other datapack biomes), but at least it prevents crashes…

I will add it to CurseForge once it's been properly tested to not cause other issues. 

I will still be leaving this issue open until a proper fix for the issue has been found.

**Comment by Hennamann** [comment]
This has now been fixed properly by only generating biome configs during world load, as data pack biomes are not added until the world loads in (since data packs can be different for each world) This means that terralith biomes now get configs generated for them and that fog customization is possible for terralith biomes, and other datapack added biomes. 

The update has already been pushed to Curse (1.5.0) https://www.curseforge.com/minecraft/mc-mods/fog-tweaker/files/3654232.
